# Site settings
title: econumi
email: info@econumi.org
description: > # this means to ignore newlines until "baseurl:"
  This is the official site for the econumi blockchain
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://econumi.org" # the base hostname & protocol for your site
twitter_username: econumi
github_username:  econumi

# Build settings
markdown: kramdown
